
package com.kema;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BindingStyleTestDocumentPortType", targetNamespace = "http://kema.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BindingStyleTestDocumentPortType {


    /**
     * 
     * @param id
     * @param name
     * @param action
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "testDocumentLiteral", targetNamespace = "http://kema.com", className = "com.kema.TestDocumentLiteral")
    public void testDocumentLiteral(
        @WebParam(name = "id", targetNamespace = "http://kema.com")
        int id,
        @WebParam(name = "name", targetNamespace = "http://kema.com")
        String name,
        @WebParam(name = "action", targetNamespace = "http://kema.com")
        String action);

}
